package heap;

import java.io.*;
import java.util.*;

public class dbquery{
	static int pageSize = 0;
	static int pagesSearched = 0;
	static int buildingsFound = 0;
	static String searchQuery;
	static long startTime = 0;
	static long endTime = 0;
	static ArrayList<Page> heap = new ArrayList<Page>();

	//file is read from the binary file generated by dbload
	//this also checks if file exists and if it doesnt the program will terminate
	public static void readFile(File f){
		FileInputStream fis = null;
		ObjectInputStream ois = null;
		try{
			Page page = null;
			fis = new FileInputStream(f);
			ois = new ObjectInputStream(fis);
			while(true){
				try{
					Object obj = ois.readObject();
					page = (Page)obj;
					heap.add(page);
					//System.out.println(page.getBuildings());
					search();
					heap.remove(page);
				}
				catch(EOFException eoe){
					break;
				}
			}
		}
		catch(FileNotFoundException fnf){
			System.out.println(fnf.getMessage());
			System.out.println("Terminating Program");
			System.exit(0);
		}
		catch(ClassNotFoundException cnf){
			cnf.printStackTrace();
		}
		catch(IOException e){
			e.printStackTrace();
		}
		finally{
			try{
				fis.close();
				ois.close();
			}
			catch(Exception ee){
			}
		}
	}

	//runs through each page individually and prints out the businesses that match the search query
	public static void search(){
		for (Page p:heap){
			for(Building b:p.buildings){
				
				//System.out.println(b.buildingName);
				if(b.getBuildingName()!=null) {
					if(b.getBuildingName().contains(searchQuery)){
						System.out.println("======================================================");
						System.out.println("Building Name: " + b.getBuildingName());
						System.out.println("Property ID: " + b.getPropID());
						System.out.println("Census year: " + b.getCensusYear());
						System.out.println("======================================================");
						System.out.println();
						buildingsFound++;
				}
			}
		}
		pagesSearched++;
		}
	}
	//print of businesses found, pages searched and time taken to search of the query
	public static void stdout(){
		System.out.println("Buildings Found: " + buildingsFound);
		System.out.println("Pages searched: "+ pagesSearched);
		System.out.println("Time Taken: " + (endTime - startTime) +"ms");	
	}

	//main runs basic checks to see if arguments were inputed correctly
	public static void main(String[] args) {
		if(args.length >= 2){
			try{
				pageSize = Integer.parseInt(args[1]);
			} 
			catch(NumberFormatException e){
				pageSize = 4096;
				System.out.println("Pagesize was not a number defaulting to 4096");
			}
			File f = new File("heap." + pageSize);
			searchQuery = args[0];

			System.out.println("Reading File");
			System.out.println(searchQuery);
			System.out.println("heap." + pageSize);
			startTime = System.currentTimeMillis();
			readFile(f);
			
			System.out.println("Searching");
			//search();
			endTime = System.currentTimeMillis();
			stdout();
					
		}
		else{
			System.out.println("Run format: java dbquery [text] [pagesize]");
		}
	}
}